### ISSUE TITLE
Edición de equipos

### ISSUE THREAD

**Issue by lmorillas** [alvaroplanas/tutorial_wagtail#2]
Este modelo https://github.com/alvaroplanas/tutorial_wagtail/blob/22abce1e0df2e7964b983ca9a4e22fdac791fe42/blogequipos/models.py#L12 no se puede editar en el admin

Haz que se pueda editar en el admin y que se vea listado de equipos en el admin (como haces con películas) y añade los datos más importantes de visualización en el listado del admin.

Deberías de tener el dato de la liga en la que juegan no?

**Comment by alvaroplanas** [comment]
Ya se puede editar los equipos en el admin y se visualizan los datos mas importantes.
No tengo la liga en la que juegan ya que la lista es de todos los equipos que han jugado en primera división y sus estadísticas.
